### ISSUE TITLE
Event handlers

### ISSUE THREAD

**Issue by MichalMisiaszek** [preetjdp/magnifier#1]
Is there a way to get event after magnification is completed where center of the glass was ?
Is is difficult to add crosshairs in the middle ?

**Comment by preetjdp** [comment]
Hey Michal.
Could you elaborate on what mean by "event after magnification completed".

Answering you second question.
It should not be difficult to add a crosshair.
Could you tell me why you'd want that?.

**Comment by preetjdp** [comment]
Hey, @MichalMisiaszek published a new version with crosshair support.

There's also added support for `CustomPainter`

https://pub.dev/packages/magnifier

**Comment by MichalMisiaszek** [comment]
Thanks, I added cross hair myself. Good job.

**Comment by preetjdp** [comment]
You're welcome.

@MichalMisiaszek Are you still looking for an Event Listener, or did you manage to do that yourself?

**Comment by MichalMisiaszek** [comment]
So in fact I learned from your code how to do it (great job again) I build dedicated magnifier myself.
Thanks again !
